spring.application.name=ParkFlow
server.port=8080

//Swagger Api
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true

//Oracle
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/orclpdb
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver