--------------------------------------------------------
--  已建立檔案 - 星期五-4月-18-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PARKING_REQUEST
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PARKING_REQUEST" 
   (	"ID" NUMBER, 
	"START_DATE" DATE, 
	"CELLPHONE" VARCHAR2(50 BYTE), 
	"CAR_NUMBER" VARCHAR2(50 BYTE), 
	"CAR_TYPE" VARCHAR2(50 BYTE), 
	"PARKING_SLOT_NUMBER" NUMBER, 
	"STATUS" NUMBER DEFAULT 1, 
	"APPLICANT_ID" NUMBER, 
	"APPLICATION_TIME" TIMESTAMP (6), 
	"REVIEW_ID" NUMBER, 
	"REVIEW_TIME" TIMESTAMP (6), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP -- 修改時間

   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007645
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007645" ON "SYSTEM"."PARKING_REQUEST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRG_PARKING_REQUEST_ID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_PARKING_REQUEST_ID" 
BEFORE INSERT ON PARKING_REQUEST
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_PARKING_REQUEST.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER "SYSTEM"."TRG_PARKING_REQUEST_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PARKING_REQUEST_UPDATED_AT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_PARKING_REQUEST_UPDATED_AT" 
BEFORE UPDATE ON PARKING_REQUEST
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/
ALTER TRIGGER "SYSTEM"."TRG_PARKING_REQUEST_UPDATED_AT" ENABLE;
--------------------------------------------------------
--  Constraints for Table PARKING_REQUEST
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PARKING_REQUEST" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARKING_REQUEST
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PARKING_REQUEST" ADD CONSTRAINT "FK_REQUEST_APPLICANT" FOREIGN KEY ("APPLICANT_ID")
	  REFERENCES "SYSTEM"."USERS" ("ID") ENABLE;
  ALTER TABLE "SYSTEM"."PARKING_REQUEST" ADD CONSTRAINT "FK_REQUEST_REVIEWER" FOREIGN KEY ("REVIEW_ID")
	  REFERENCES "SYSTEM"."USERS" ("ID") ENABLE;
