--------------------------------------------------------
--  已建立檔案 - 星期五-4月-18-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PARKING_QUOTA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PARKING_QUOTA" 
   (	"ID" NUMBER, 
	"START_DATE" DATE, 
	"TOTAL_SLOTS" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP -- 修改時間

   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007646
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007646" ON "SYSTEM"."PARKING_QUOTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRG_PARKING_QUOTA_ID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_PARKING_QUOTA_ID" 
BEFORE INSERT ON PARKING_QUOTA
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_PARKING_QUOTA.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER "SYSTEM"."TRG_PARKING_QUOTA_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PARKING_QUOTA_UPDATED_AT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_PARKING_QUOTA_UPDATED_AT" 
BEFORE UPDATE ON PARKING_QUOTA
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/
ALTER TRIGGER "SYSTEM"."TRG_PARKING_QUOTA_UPDATED_AT" ENABLE;
--------------------------------------------------------
--  Constraints for Table PARKING_QUOTA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PARKING_QUOTA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
