--------------------------------------------------------
--  已建立檔案 - 星期五-4月-18-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."USERS" 
   (	"ID" NUMBER, 
	"CHINESE_NAME" VARCHAR2(255 CHAR), 
	"ENGLISH_NAME" VARCHAR2(255 CHAR), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"CELLPHONE" VARCHAR2(255 CHAR), 
	"CAR_NUMBER" VARCHAR2(255 CHAR), 
	"CAR_TYPE" VARCHAR2(255 CHAR), 
	"ROLE_ID" NUMBER DEFAULT 1, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP -- 修改時間

   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."USERS"."ROLE_ID" IS '1: 一般使用者/2: FM';
--------------------------------------------------------
--  DDL for Index SYS_C007643
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007643" ON "SYSTEM"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRG_USERS_ID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_USERS_ID" 
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_USERS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER "SYSTEM"."TRG_USERS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_USERS_UPDATED_AT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_USERS_UPDATED_AT" 
BEFORE UPDATE ON USERS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/
ALTER TRIGGER "SYSTEM"."TRG_USERS_UPDATED_AT" ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."USERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."USERS" ADD CONSTRAINT "FK_USERS_ROLE" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "SYSTEM"."ROLE" ("ID") ENABLE;
